### ISSUE TITLE
Nothing happened.

### ISSUE THREAD

**Issue by fxzxmicah** [iTaysonLab/jetispot#34] opened 2023-10-02 06:19 UTC
When I clicked sign in button, I waited a long time and nothing happened.

**Comment by iTaysonLab** [comment] 2023-10-16 06:17
Duplicate of #32 :(

**Closed as not planned by iTaysonLab** 2023-10-16 06:17 UTC

**Comment by fxzxmicah** [comment] 2023-10-16 12:17
@iTaysonLab I don't think this is duplicate. There was no prompt after I clicked the sign in button.

**Comment by fxzxmicah** [comment] 2023-12-06 03:45
@iTaysonLab My problem is that the app made an udp request to `time.google.com:123` before logging in, and my VPN doesn't support udp. That's why I can't log in, so this is not a duplicate.

**Comment by iTaysonLab** [comment] 2023-12-06 03:50
> @iTaysonLab My problem is that the app made an udp request to `time.google.com:123` before logging in, and my VPN doesn't support udp. That's why I can't log in, so this is not a duplicate.

I don't think should be an application issue. librespot-java actually uses this request to know the current time, but what I can do is provide alternative solutions for people with your issue

**Comment by fxzxmicah** [comment] 2023-12-06 04:00
At least it's a feature request. 😁
