### ISSUE TITLE
Can't sign in with Premium Family

### ISSUE THREAD

**Issue by LordImmaculate** [iTaysonLab/jetispot#33] opened 2023-08-30 08:22 UTC
I can't sign in with Premium Family. I am not the one who pays. It says "You need Spotify Premium to use JeriSpot"

**Comment by 0lle0nline** [comment] 2023-09-09 19:02
I'm having the same issue on Pixel 6a running GrapheneOS

**Comment by utada1stlove** [comment] 2023-10-16 06:05
same on oneplus8 running OOS

**Comment by iTaysonLab** [comment] 2023-10-16 06:17
Duplicate of #32 :(

**Closed as not planned by iTaysonLab** 2023-10-16 06:17 UTC
